#pragma once

#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)

#define SD_MAX_BONES_WGPU 128
#define SD_MAX_COLORS_WGPU 8
#define SD_MAX_CASCADES 4
#define SD_MAX_LIGHTS 512
#define SD_MAX_LIGHTS_PER_TILE 64
#define SD_TILE_SIZE 16
#define SD_INVALID_LIGHT_IDX 0xFFFFFFFF

#define SHADER_DEFS_WGSL \
    "const MAX_BONES: u32 = " STRINGIFY(SD_MAX_BONES_WGPU) ";\n" \
    "const MAX_COLORS: u32 = " STRINGIFY(SD_MAX_COLORS_WGPU) ";\n" \
    "const MAX_CASCADES: u32 = " STRINGIFY(SD_MAX_CASCADES) ";\n" \
    "const MAX_LIGHTS: u32 = " STRINGIFY(SD_MAX_LIGHTS) ";\n" \
    "const MAX_LIGHTS_PER_TILE: u32 = " STRINGIFY(SD_MAX_LIGHTS_PER_TILE) ";\n" \
    "const TILE_SIZE: u32 = " STRINGIFY(SD_TILE_SIZE) ";\n" \
    "const INVALID_LIGHT_IDX: u32 = " STRINGIFY(SD_INVALID_LIGHT_IDX) ";\n" \
    "\n"
//
//#undef STRINGIFY_HELPER
//#undef STRINGIFY
